CC=g++
CFLAGS=\
	-O0                     \
	-std=c++17              \
	-pedantic               \
	-W                      \
	-Wall                   \
	-Wconversion            \
	-Wctor-dtor-privacy     \
	-Weffc++                \
	-Wenum-compare          \
	-Werror                 \
	-Wextra                 \
	-Wfloat-equal           \
	-Wlogical-op            \
	-Wnon-virtual-dtor      \
	-Wold-style-cast        \
	-Woverloaded-virtual    \
	-Wshadow                \
	-Wsign-conversion       \
	-Wstrict-overflow=2     \
	-Wunreachable-code
EXECUTABLE=main.exe


all:
	$(CC) $(CFLAGS) main.cpp -o $(EXECUTABLE)
